server:
  port: 9005

application:
  name: Service Account Management 
  description: API created to manage accounts 
  
spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: canelabank@gmail.com
      password: qmippwdhmjtcyukd
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
